POST http://localhost:3003/api/blogs 
Content-Type: application/json

{
    "title": "uusikokeilu",
    "author": "Maija",
    "url": "urururur",
    "likes": "8",
    "userId": "5cc7f67d7021bb1926821afe"
    }